# version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disables security for development
      - logger.org.elasticsearch=warn # Set logging level to warn instead of info
    ports:
      - "9200:9200"  # Elasticsearch REST API port
      - "9300:9300"  # Elasticsearch transport port
    # networks:
    #   - app-network
    # volumes:
    #   - es_data:/usr/share/elasticsearch/data
  
  # ollama:
  #   image: ollama/ollama  # Assuming the Ollama CLI image
  #   container_name: ollama
  #   volumes:
  #     - ./ollama/ollama:/root/.ollama  # Mount volume to store the model
  #   command: >
  #     sh -c "
  #     ollama pull microsoft/phi3 &&
  #     ollama serve --model /app/data/microsoft-phi3"
  #   ports:
  #     - "11434:11434"
  #   restart: unless-stopped

  streamlit-app:
    build: 
      context: .  # Path to your Streamlit app folder
      dockerfile: Dockerfile
    container_name: az900_study_buddy_app
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - WORKDIR=${WORKDIR}
      - INDEX_NAME=${INDEX_NAME}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_API_KEY=${OLLAMA_API_KEY}
    ports:
      - "8501:8501"  # Streamlit's default port
    # networks:
    #   - app-network
    # volumes:
    #   - ./app:/app
# networks:
#   app-network:
#     driver: bridge

# volumes:
#   es_data:
#     driver: local
